version: "3.3"
services:
    mqtt-publisher:
        build: .
        hostname: mqtt-publisher
        container_name: mqtt-publisher
        restart: unless-stopped
        image: eclipse-mosquitto
        command: /usr/bin/python /app/mqtt_pub.py --conf /app/pub_conf.json --data /app/data.json
        volumes:
          - ./logs:/app/logs
        network_mode: host 

    mqtt-subscriber:
        build: .
        hostname: mqtt-subscriber
        container_name: mqtt-subscriber
        restart: unless-stopped
        image: eclipse-mosquitto
        command: /usr/bin/python /app/mqtt_sub.py --conf /app/sub_conf.json 
        volumes:
          - ./logs:/app/logs
        network_mode: host 